# Please DO NOT change version number!
version: 2

# 
# Feel free to set up your own items for the Ancient Traveler. Remember to follow the formatting.
# In case of any issues, feel free to contact us on our Discord server.
# 
items:
    '1': amethyst shard
    '2': heart of the sea
    '3': shulker shell
    '4': diamond horse armor
    '5': enchanted golden apple
    '6': totem of undying
    '7': bamboo
    '8': turtle shell
    '9': dragon breath
    '10': trident
    '11': netherite ingot
    '12': harm arrow 2
    '13': strength potion 2
    '14': splash healing potion 2
    '15': splash instant damage 2
    '16': looting
    '17': smite
    '18': feather falling
    '19': frost walker
    '20': piercing
    '21': quick charge
    '22': luck of the sea

# Item stock refresh cooldown in hours.
refresh_cooldown: 24
